FROM ubuntu:latest

ENV PYTHONDONTWRITEBYTECODE=1

RUN apt update
RUN apt install -y python3-pip

COPY req.txt req.txt
RUN pip install -r req.txt

COPY fasttask /fasttask
WORKDIR /fasttask
