version: "3.9"

services:
  fasttask:
    image: fasttask
    container_name: fasttask 
    restart: always
    command: sh run.sh
    ports:
      - "9001:80"
    volumes:
      - ./files:/fasttask/files
 