version: "3.9"

services:
  fasttask:
    image: fasttask
    restart: always
    command: bash -c "celery multi start w1 -A celery_task -l info && uvicorn api:app --host 0.0.0.0 --port 80 --reload"
    ports:
          - "8080:80"

  redis:
    image: redis:alpine
    restart: always
    expose:
      - '6379'
