version: "3.9"

services:
  redis:
    image: redis:alpine
    restart: always
    expose:
      - '6379'

  fasttask:
    image: fasttask
    restart: always
    command: sh run.sh
    depends_on:
      - redis
    ports:
      - "9001:80"
