services:
  fasttask-desktop-master:
    image: fasttask:desktop-test
    container_name: fasttask-desktop-master
    restart: always

    security_opt:
      - seccomp:unconfined

    ports:
      # 在single_node 与 distributed_master 需要映射api端口 
      - "9002:443"
      # 在distributed_master需要映射任务队列端口
      - "9000:6379"
      
      # webtop  related
      - 3003:3000

    volumes:
      - ./fasttask-desktop-master-files:/fasttask/files

    environment:


      # # distributed_master: 分布式部署部署的主节点 提供api与任务队列后端
      - node_type=distributed_master
      - TASK_QUEUE_PASSWD=passwd

      - RESULT_EXPIRES=3600
      - WORKER_POOL=prefork
      - WORKER_CONCURRENCY=4

      # api设置
      - API_DOCS=True
      - API_REDOC=True
      - API_STATUS_INFO=True
      - API_RUN=True
      - API_CREATE=True
      - api_check=True
      - API_REVOKE=True
      - API_FILE_DOWNLOAD=True
      - API_FILE_UPLOAD=True

      # webtop  related
      - PUID=1000
      - PGID=1000
      - TITLE=fasttask-desktop
      - PASSWORD=webtop_passwd


  fasttask-desktop-worker-get_circle_area:
    image: fasttask:desktop-test
    container_name: fasttask-desktop-worker-get_circle_area
    restart: always

    security_opt:
      - seccomp:unconfined

    ports:
      # webtop  related
      - 3001:3000

    volumes:
      - ./fasttask-desktop-worker-files:/fasttask/files

    environment:

      # distributed_worker: 分布式部署部署的从节点 负责cerery任务执行环境,需要配置distributed_master的主机地址, 任务队列端口与密码
      - node_type=distributed_worker
      - master_host=0.0.0.0
      - TASK_QUEUE_PORT=9000
      - TASK_QUEUE_PORT=passwd
      
      # 启用的任务
      - ENABLED_TASKS=get_circle_area
      # 禁用的任务
      - DISABLED_TASKS=get_hypotenuse

      - RESULT_EXPIRES=3600
      - WORKER_POOL=prefork
      - WORKER_CONCURRENCY=4
      
      # webtop  related
      - PUID=1000
      - PGID=1000
      - TITLE=fasttask-desktop-worker
      - PASSWORD=passwd



  fasttask-desktop-worker-get_hypotenuse:
    image: fasttask:desktop-test
    container_name: fasttask-desktop-worker-get_hypotenuse
    restart: always

    security_opt:
      - seccomp:unconfined

    ports:
      # webtop  related
      - 3002:3000

    volumes:
      - ./fasttask-desktop-worker-files:/fasttask/files

    environment:

      # distributed_worker: 分布式部署部署的从节点 负责cerery任务执行环境,需要配置distributed_master的主机地址, 任务队列端口与密码
      - node_type=distributed_worker
      - master_host=0.0.0.0
      - TASK_QUEUE_PORT=9000
      - TASK_QUEUE_PASSWD=passwd
      
      # 启用的任务
      - ENABLED_TASKS=get_hypotenuse
      # 禁用的任务
      - DISABLED_TASKS=get_circle_area
    
      - RESULT_EXPIRES=3600
      - WORKER_POOL=prefork
      - WORKER_CONCURRENCY=4

      # webtop  related
      - PUID=1000
      - PGID=1000
      - TITLE=fasttask-desktop-worker
      - PASSWORD=passwd

    