services:
  fasttask-desktop-master:
    image: irid/fasttask:desktop-test
    container_name: fasttask-desktop-master
    restart: always

    security_opt:
      - seccomp:unconfined

    ports:
      # 在single_node 与 distributed_master 需要映射api端口 
      - "9001:443"
      # 在distributed_master需要映射任务队列端口
      - "9000:6379"
      # webtop  related
      - 3000:3000

    volumes:
       - ./files:/fasttask/files

    environment:
      - NODE_TYPE=distributed_master
      - TASK_QUEUE_PASSWD=passwd

      # webtop  related
      - PUID=1000
      - PGID=1000
      - TITLE=fasttask-desktop
      - PASSWORD=webtop_passwd


  fasttask-desktop-worker-get_circle_area:
    image: irid/fasttask:desktop-test
    container_name: fasttask-desktop-worker-get_circle_area
    restart: always

    security_opt:
      - seccomp:unconfined

    ports:
      # webtop  related
      - 3001:3000

    volumes:
      - ./files-worker_1:/fasttask/files

 
    environment:
      - NODE_TYPE=distributed_worker
      - MASTER_HOST=10.65.8.8
      - TASK_QUEUE_PORT=9000
      - TASK_QUEUE_PASSWD=passwd

      # webtop  related
      - PUID=1000
      - PGID=1000
      - TITLE=fasttask-desktop-worker
      - PASSWORD=passwd

  fasttask-desktop-worker-get_hypotenuse:
    image: irid/fasttask:desktop-test
    container_name: fasttask-desktop-worker-get_hypotenuse
    restart: always


    security_opt:
      - seccomp:unconfined

    ports:
      # webtop  related
      - 3002:3000

    volumes:
      - ./files-worker_2:/fasttask/files

    environment:
      - NODE_TYPE=distributed_worker
      - MASTER_HOST=10.65.8.8
      - TASK_QUEUE_PORT=9000
      - TASK_QUEUE_PASSWD=passwd

      # webtop  related
      - PUID=1000
      - PGID=1000
      - TITLE=fasttask-desktop-worker
      - PASSWORD=passwd

    