services:
  master:
    image: fasttask:test
    container_name: fasttask-master
    command: ["python", "run.py"]
    restart: always

    ports:
      - "9001:443"
      - "9000:6379"

    volumes:
      - ./files-master:/fasttask/files

    environment:
      - NODE_TYPE=distributed_master
      - TASK_QUEUE_PASSWD=passwd
      - SOFT_TIME_LIMIT=120

  worker-get_circle_area:
    image: fasttask:test
    container_name: fasttask-worker-get_circle_area
    command: ["python", "run.py"]
    restart: always

    volumes:
      - ./files-worker_1:/fasttask/files

    environment:
      - NODE_TYPE=distributed_worker
      - MASTER_HOST=10.65.8.8
      - TASK_QUEUE_PORT=9000
      - TASK_QUEUE_PASSWD=passwd
      - ENABLED_TASKS=get_circle_area
      - DISABLED_TASKS=get_hypotenuse
      - WORKER_CONCURRENCY=32
      - SOFT_TIME_LIMIT=120

  worker-get_hypotenuse:
    image: fasttask:test
    container_name: fasttask-worker-get_hypotenuse
    command: ["python", "run.py"]
    restart: always

    volumes:
      - ./files-worker_2:/fasttask/files

    environment:

      - NODE_TYPE=distributed_worker
      - MASTER_HOST=10.65.8.8
      - TASK_QUEUE_PORT=9000
      - TASK_QUEUE_PASSWD=passwd
      - ENABLED_TASKS=get_hypotenuse
      - DISABLED_TASKS=get_circle_area
      - WORKER_CONCURRENCY=32
      - SOFT_TIME_LIMIT=120
