services:
  master:
    image: irid/fasttask:test
    container_name: fasttask-master
    restart: always

    ports:
      - "9001:443"
      - "9000:6379"

    volumes:
      - ./files:/fasttask/files

    environment:
      - NODE_TYPE=distributed_master
      - TASK_QUEUE_PASSWD=passwd

  worker-get_circle_area:
    image: irid/fasttask:test
    container_name: fasttask-worker-get_circle_area
    restart: always

    volumes:
      - ./files-worker_1:/fasttask/files

    environment:
      - NODE_TYPE=distributed_worker
      - MASTER_HOST=10.65.8.8
      - TASK_QUEUE_PORT=9000
      - TASK_QUEUE_PASSWD=passwd

  worker-get_hypotenuse:
    image: irid/fasttask:test
    container_name: fasttask-worker-get_hypotenuse
    restart: always

    volumes:
      - ./files-worker_2:/fasttask/files

    environment:

      - NODE_TYPE=distributed_worker
      - MASTER_HOST=10.65.8.8
      - TASK_QUEUE_PORT=9000
      - TASK_QUEUE_PASSWD=passwd
